- id: clevercsv-standardize
  name: CleverCSV Standardize
  entry: clevercsv standardize
  language: python
  types: [csv]
  args: ["--in-place"]
  require_serial: false
  additional_dependencies: []
